language: node_js

env:
  - CXX=g++-4.8

node_js:
  - 6
  - 8
  - 10

notifications:
  email:
    - lilleman@larvit.se

before_install:
  - $CXX --version

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - npm i

before_script:
  - mysql -e 'CREATE DATABASE test'

script: DB_CONF_FILE=../config/db_travis.json node_modules/.bin/istanbul cover mocha test/test.js --exit
script: ./node_modules/eslint/bin/eslint.js ./

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

services:
  - mysql

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

#addons:
#  mariadb:
#    - 5.5
#    - 10.0
#    - 10.1
